# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "NrcG4orwnxo/n2HeRUFvw/B/kMuKVbABg+xeJtfzfiTRNQLJdKN6sJNEsoqr87XVIJzKhWs+O8spePwK9Q4oSzz5+7VDQJGrKcftrDm2HAgLU0ObWgoHZqX2MAEE0XyUjL+UApZlWVnd2rKj/umEkTxDDwyaEHGA9/TerGGe/HZi7IOORDworZbBxVnK2h8FlQNoSIYGIF6Vueh7gIk/rq/Yk/PjIEAoYUlHp6rSC2//QSSLkov3X1wxz3dc4K89Lzr2szI2/rmwVnG4zPwDXFOpZulH1xrRoczpy8svSwaQB8z2/XSEAZ6wC46MJ77kMYIRydzuKLk8NCQKkm6KW/hqpwgDOXae4Jywoow1BX6QTjKGC3U+R691a8eCqBl7kYAEq6YMqjld6CNy6bsmpIg4yyprHYLgDkK4ShPhT6+KLy8dj2+OytiqacGkSDHJqxhRZDuCs3xOk/hsr15uxRyl6nh+ogvsgBnyuKTH+y3J7lAigMcssebik73z4PwtrUlOC/kwyjbG2hIMnua7QfyNAx2dW8i3DH1ZPrjG7Nw9pJFmxrq9G3lwNOIlz95jT1hKlZYcC/qRT4bODyfD0iVb6SLjDAFvMlvnph4DxEHt8sprZvUb07x5JNaAO/oMnqTWVD6UnuWnlrj66SmTfixR+985jEg7OK9QmLwVejU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml