appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: NrcG4orwnxo/n2HeRUFvw/B/kMuKVbABg+xeJtfzfiTRNQLJdKN6sJNEsoqr87XVIJzKhWs+O8spePwK9Q4oSzz5+7VDQJGrKcftrDm2HAgLU0ObWgoHZqX2MAEE0XyUjL+UApZlWVnd2rKj/umEkTxDDwyaEHGA9/TerGGe/HZi7IOORDworZbBxVnK2h8FlQNoSIYGIF6Vueh7gIk/rq/Yk/PjIEAoYUlHp6rSC2//QSSLkov3X1wxz3dc4K89Lzr2szI2/rmwVnG4zPwDXFOpZulH1xrRoczpy8svSwaQB8z2/XSEAZ6wC46MJ77kMYIRydzuKLk8NCQKkm6KW/hqpwgDOXae4Jywoow1BX6QTjKGC3U+R691a8eCqBl7kYAEq6YMqjld6CNy6bsmpIg4yyprHYLgDkK4ShPhT6+KLy8dj2+OytiqacGkSDHJqxhRZDuCs3xOk/hsr15uxRyl6nh+ogvsgBnyuKTH+y3J7lAigMcssebik73z4PwtrUlOC/kwyjbG2hIMnua7QfyNAx2dW8i3DH1ZPrjG7Nw9pJFmxrq9G3lwNOIlz95jT1hKlZYcC/qRT4bODyfD0iVb6SLjDAFvMlvnph4DxEHt8sprZvUb07x5JNaAO/oMnqTWVD6UnuWnlrj66SmTfixR+985jEg7OK9QmLwVejU=}
