travis:
  secure:
    BINSTAR_TOKEN: ZoGocwHruYXLWtGSjp1ks0maYtnrd5EY47WGFyeOI3PJcLvNXfJHhcJmldkKaiJbo9EgAuHT5NL7qMoOyvDXiE43GKU9JWdDsy67smdCE7unKXybYlv5LejHLxkdZjEALgd2QCvoCn3w1DUYiny68Uac9l/xHmnaLnclUWAfNyvAM+Axik0uPtUNyNUT7kiDSOnxfVlf/j8rMEldt+rnLy2MxmkKsUErpPvmKnBoGsO4k39XOhFCS7mZGIATkJaq8CXSa2A97vU9m5booPzJDSQ7VYUeqQNhptFiP14fLFNCNLO3913pgtO5PXKt90lGpPOYnrPjj/eDdQ4N1hp4KLBE8gb4OmuGJqYQ/WgkdoEEL0oVosLPlSTfKkwJ+FEjauueYDR8vA88yUoXYTCA9hC5/MNquLf5S9nTvqnEV4t4jhggsa0yjZTO3PoawNbJETu6PsQ5olVLvqZT9bTk4QeE76tM+Poe5sBzHb4aQGHJPpl9BsOUg5UdB/J1n1wG60qeL4lu8Q4K1A/PPC22RV+CiLoSxIB3Kh2DZAS+t3yyO21Nf4htC8n3JjHR/sRrVr5kNE/sY92aJcyiVkvslMe9VHdw2kVCPTJJCo3kdZ0jukYuKIFRDYYV0PoXF/aLM+FnsTAZd3OzvRWFDTm1C2Z0PGif3WqYyQB9ZbFgov8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
